server:
  port: 8080

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/snaker?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: rootroot
      driver-class-name: com.mysql.jdbc.Driver